name: NodeJS CI with PostgreSQL - now

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Coder123
          POSTGRES_DB: ts_mocha_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Create PostgreSQL tables
        run: PGPASSWORD=coder123 psql -h localhost -U coder -d ts_mocha_db -a -f ./tables.sql
      - name: Run tests with PostgreSQL
        run: npm test
        env:
          DATABASE_URL: postgres://postgres:Coder123@localhost:5432/ts_mocha_db
